# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: true  # whether to fetch clean each time
  fetchDepth: 1  # the depth of commits to ask Git to fetch
  lfs: false  # whether to download Git-LFS files
  submodules: true  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
  path: _work\Team\Arrakis\BaD\  # path to check out source code, relative to the agent's build directory (e.g. \_work\1)
  persistCredentials: false  # set to 'true' to leave the OAuth token in the Git config after the initial fetch

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true